name: nemos
channels:
  - conda-forge
  - nvidia
dependencies:
  - ffmpeg
  - jax
  - jaxlib=*=*cuda*
  - cuda-nvcc
  - pip:
      - git+https://github.com/flatironinstitute/ccn-software-fens-2024.git
