#!/bin/bash

CONDA_OVERRIDE_CUDA="12.3" conda env update -p $NB_PYTHON_PREFIX --file environment-cuda.yml
conda activate fens2024
conda clean --all -y
# because of symlinks and being in the container, this is where the Binder
# instance thinks the data should go.
FENS_DATA_DIR=/home/jovyan/data python ccn-software-fens-2024/scripts/setup.py
cp -R ccn-software-fens-2024/notebooks ./notebooks
